# See https://prometheus.io/docs/alerting/latest/configuration/ for details.

global:

receivers:
  - name: 'team-X'
    webhook_configs:
      - url: 'http://webhook.url'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: team-X
  routes:
    - matchers:
        - alert_kind="error"
      group_interval: 24h
      receiver: team-X
