ch:
  dsn: 'clickhouse://default:@clickhouse:9000/uptrace?sslmode=disable'

##
projects:
  - id: 1
    name: Uptraceaa
    token: project1_secret_token
    pinned_attrs:
      - service.name
      - host.name
      - deployment.environment
    group_by_env: false
    group_funcs_by_service: false

  - id: 2
    name: My project
    token: project2_secret_token
    pinned_attrs:
      - service.name
      - host.name
      - deployment.environment
    group_by_env: false
    group_funcs_by_service: false

metrics_from_spans:
  - name: uptrace.tracing.spans_duration
    description: Spans duration (excluding events)
    instrument: histogram
    unit: microseconds
    value: span.duration / 1000
    attrs:
      - span.system as system
      - service.name as service
      - host.name as host
      - span.status_code as status
    where: not span.is_event

  - name: uptrace.tracing.spans
    description: Spans count (excluding events)
    instrument: counter
    unit: 1
    value: span.count
    attrs:
      - span.system as system
      - service.name as service
      - host.name as host
      - span.status_code as status
    where: not span.is_event

  - name: uptrace.tracing.events
    description: Events count (excluding spans)
    instrument: counter
    unit: 1
    value: span.count
    attrs:
      - span.system as system
      - service.name as service
      - host.name as host
    where: span.is_event

alerting:
  create_alerts_from_spans:
    enabled: true
    labels:
      alert_kind: error

alertmanager_client:
  urls:
    - 'http://alertmanager:9093/api/v2/alerts'

ch_schema:
  compression: ZSTD(3)
  replicated: false
  spans:
    storage_policy: 'default'
    ttl_delete: 120 DAY
  metrics:
    storage_policy: 'default'
    ttl_delete: 180 DAY

listen:
  grpc:
    addr: ':14317'
  http:
    addr: ':14318'

site:
  #addr: 'https://localhost:14318'

spans:

db:
  driver: sqlite
  dsn: 'file:uptrace.sqlite3?_pragma=foreign_keys(1)&_pragma=busy_timeout(1000)'

secret_key: cb615dcf3c717c0b59290683c275ef78
debug: false
