services:
  app:
    image: jaegertracing/all-in-one:2
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - traefik

networks:
  traefik:
    external: true
