services:
  app:
    image: dexidp/dex:v2.39.1
    container_name: dexidp
    restart: unless-stopped
    command: dex serve /app/config.yaml
    volumes:
      - ./config/config.yaml:/app/config.yaml
      - ./data:/app/data
    networks:
      - traefik

networks:
  traefik:
    external: true
