services:
  dexidp:
    image: dexidp/dex
    container_name: dexidp
    restart: unless-stopped
    networks:
      - traefik
    command: "dex serve /app/config.yaml"
    user: root
    volumes:
      - ./config/config.yaml:/app/config.yaml
      - ./data:/app/data

networks:
  traefik:
    external: true
    name: traefik
