http:
  middlewares:
    google-auth:
      forwardAuth:
        address: 'https://auth.demo.io'
    ip-list:
      ipWhiteList:
        sourceRange:
          - '127.0.0.1'
    cf-real-ip:
      plugin:
        traefik-real-ip:
          Proxy:
            - proxyHeadername: cdn-loop
              proxyHeadervalue: cloudflare
              realIP: Cf-Connecting-Ip
              OverwriteXFF: true
    jwt-auth:
      plugin:
        traefik-auth:
          JwtHeaders:
            Subject: sub
          Keys:
            - https://samples.auth0.com/.well-known/jwks.json
            - |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSv
              vkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHc
              aT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIy
              tvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0
              e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWb
              V6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9
              MwIDAQAB
              -----END PUBLIC KEY-----
            - https://openid.demo.io/.well-known/jwks.json
  routers:
    nginx:
      entryPoints:
        - 'https'
      rule: 'Host(`demo.io`)'
      service: 'nginx'
      tls:
        certResolver: default
    nginx-default-tls:
      entryPoints:
        - 'https'
      rule: 'Host(`da.demo.io`)'
      service: 'nginx'
      tls: true
    nginx-default-dns-tls:
      entryPoints:
        - 'https'
      rule: 'Host(`ds.demo.io`)'
      service: 'nginx'
      tls:
        certResolver: dns
        domains:
          - main: 'ds.demo.io'
            sans:
              - '*.demo.io'
  services:
    nginx:
      loadBalancer:
        servers:
          - url: 'http://nginx'
