services:
  app:
    container_name: matrix
    image: jevolk/tuwunel:v1.5.1
    restart: always
    user: 1000:1000
    networks:
      - traefik
    volumes:
      - ./data/db:/var/lib/tuwunel
      - ./data/config.toml:/etc/config.toml
    environment:
      TUWUNEL_CONFIG: /etc/config.toml

networks:
  traefik:
    external: true
