version: '3'

services:
  matrix:
    image: matrixdotorg/dendrite-monolith:v0.10.8
    restart: always
    container_name: matrix
    volumes:
      - ./data/matrix:/etc/dendrite
      - ./config/dendrite.yaml:/etc/dendrite/dendrite.yaml
      - ./data/media:/var/dendrite/media
    networks:
      - proxy
    depends_on:
      - matrix-db
    networks:
      - proxy
    restart: unless-stopped
  matrix-db:
    hostname: postgres
    container_name: matrix-db
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - ./config/create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: b24478d0-df2e-4f94-a185-d01f9da7af25
      POSTGRES_USER: dendrite
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dendrite"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - proxy
networks:
  proxy:
    external: true
    name: proxy

