services:
  app:
    image: matrixconduit/matrix-conduit:v0.10.5
    restart: unless-stopped
    container_name: matrix
    volumes:
      - ./db:/var/lib/matrix-conduit/
    environment:
      CONDUIT_SERVER_NAME: your.server.name # EDIT THIS
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/matrix.db
      CONDUIT_DATABASE_BACKEND: sqlite
      CONDUIT_PORT: 6167
      CONDUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
      CONDUIT_ALLOW_REGISTRATION: 'true'
      CONDUIT_ALLOW_FEDERATION: 'true'
      CONDUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
      CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
      #CONDUIT_MAX_CONCURRENT_REQUESTS: 100
      CONDUIT_ADDRESS: 0.0.0.0
      CONDUIT_CONFIG: '' # Ignore this
    networks:
      - traefik
networks:
  traefik:
    external: true
    name: traefik
