services:
  redis:
    image: redis:7.0.7
    container_name: redis
    networks:
      - traefik
    restart: always
    volumes:
      - ./redis:/data

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - traefik

  postgres-admin:
    image: adminer
    restart: always
    container_name: postgres-admin
    networks:
      - traefik

  s3:
    image: minio/minio:RELEASE.2023-01-06T18-11-18Z
    container_name: s3
    restart: always
    volumes:
      - ./s3:/data
    networks:
      - traefik
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    command: server /data/data --console-address ":9001"

networks:
  traefik:
    external: true
    name: traefik
