services:
  app:
    image: adminer:latest
    container_name: adminer
    volumes:
      - ./plugins:/var/www/html/plugins-enabled
    networks:
      - traefik

networks:
  traefik:
    external: true
