version: "3.7"

services:
  desktop:
    container_name: ${POD_NAME}
    hostname: ${POD_HOSTNAME}
    image: ${POD_IMAGE}
    restart: always
    volumes:
      - ${POD_DATA}:/usr/share/nginx/html
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.${POD_NAME}.middlewares=basicAuth"
      - "traefik.http.routers.${POD_NAME}.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.${POD_NAME}.tls.certResolver=default"
      - "traefik.http.routers.${POD_NAME}.rule=Host(`${POD_URL}`)"
      - "traefik.http.routers.${POD_NAME}.service=${POD_NAME}"
      - "traefik.http.services.${POD_NAME}.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
