apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 10.2.0.6
    k0sApiPort: 9443
    port: 6443
  controllerManager:
    extraArgs:
      flex-volume-plugin-dir: "/var/lib/kubelet/volume-plugins"
  workerProfiles:
    - name: coreos
      values:
        volumePluginDir: /var/lib/kubelet/volume-plugins
  extensions:
    helm:
      repositories:
      - name: cilium
        url: https://helm.cilium.io
      - name: metallb
        url: https://metallb.github.io/metallb
      - name: jetstack
        url: https://charts.jetstack.io
      charts:
      - name: metallb
        chartname: metallb/metallb
        namespace: kube-system
      - name: jetstack
        chartname: cert-manager
        namespace: cert-manager
      - chartname: cilium/cilium
        name: cilium
        namespace: kube-system
        values: |
          k8sServiceHost: 10.2.0.6
          k8sServicePort: 6443
          hubble:
            enabled: true
            relay:
              enabled: true
            ui:
              enabled: true
          operator:
            enabled: true
            replicas: 1
          kubeProxyReplacement: "strict"
          ingressController:
            enabled: true
            loadbalancerMode: shared
        version: 1.13.2
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    kubeProxy:
      disabled: true
    podCIDR: 10.244.0.0/16
    provider: custom
    serviceCIDR: 10.96.0.0/12
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  storage:
    type: etcd
  telemetry:
    enabled: true
