services:
  app:
    container_name: vault
    image: hashicorp/vault:1.17
    restart: on-failure
    command:
      - vault
      - server
      - -dev
      - -dev-listen-address=0.0.0.0:8200
    environment:
      VAULT_API_ADDR: http://localhost:8200
      VAULT_ADDR: http://localhost:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data:/vault/data
    networks:
      - traefik

networks:
  traefik:
    external: true
