services:
  vault:
    container_name: vault
    image: vault:1.9.10
    restart: on-failure
    command:
      - 'vault'
      - 'server'
      - '-dev'
      - '-dev-listen-address=0.0.0.0:8200'
    environment:
      VAULT_API_ADDR: http://localhost:8200
      VAULT_ADDR: http://localhost:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/file:/vault/file
      - ./data/logs:/vault/logs
      - ./data/config:/vault/config
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
