#!/bin/sh
NAME="proxy"
EXEC="sh"

## check docker running.
if ! docker info >/dev/null 2>&1; then
    echo "Docker does not seem to be running, exiting..."
    exit 1
fi

## init scripts.
[ "$1" = "init" ] && {
    echo 'init start services.'

    mkdir -p work/.init/

    cat <<EOF >work/.init/init.sh
#!/bin/sh
sctl enable ss
sctl enable v2ray
sctl enable wireguard
EOF

}

[ "$1" = "rm" ] && {
    docker compose down
}

[ "$1" = "e" ] && {
    if [ "$2" != "" ]; then
        EXEC=$2
    fi
    docker exec -ti $NAME $EXEC
}

[ "$1" = "run" ] && {
    docker compose down
    docker compose up -d
}

exit 0
