receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: 'promscale:9202'
    tls:
      insecure: true
    sending_queue:
      queue_size: 1000000
    timeout: 10s
  prometheusremotewrite:
    endpoint: 'http://promscale:9201/write'
    resource_to_telemetry_conversion:
      enabled: true
    tls:
      insecure: true

processors:
  batch:
    send_batch_size: 4000
    send_batch_max_size: 4000
    timeout: 10s

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
      processors: [batch]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
