services:
  station:
    container_name: station
    hostname: station
    image: zzci/station
    restart: always
    volumes:
      - ./work:/work
      - ./root:/root
      - /var/run/docker.sock:/var/run/docker.sock
      - /app:/app
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
