services:
  clickhouse:
    container_name: uptrace-db
    image: clickhouse/clickhouse-server:24-alpine
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    networks:
      - uptrace

  uptrace:
    container_name: uptrace
    image: uptrace/uptrace:latest
    restart: on-failure
    volumes:
      - ./data/uptrace:/var/lib/uptrace
      - ./config/uptrace.yml:/etc/uptrace/uptrace.yml
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - traefik
      - uptrace

  alertmanager:
    container_name: uptrace-alert
    image: prom/alertmanager:v0.28.0
    restart: on-failure
    user: root
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/config.yml
      - ./data/alertmanager:/alertmanager
    command:
      - --config.file=/etc/alertmanager/config.yml
      - --storage.path=/alertmanager
    networks:
      - uptrace

  otel-collector:
    container_name: uptrace-otel
    image: otel/opentelemetry-collector-contrib:0.98.0
    restart: on-failure
    command:
      - --config=/etc/otelcol/config.yaml
    volumes:
      - ./config/otel.yml:/etc/otelcol/config.yaml
    networks:
      - uptrace
      - traefik

networks:
  uptrace:
    name: uptrace
  traefik:
    external: true
