version: "3"

services:
  clickhouse:
    container_name: uptrace-db
    image: clickhouse/clickhouse-server:22.9-alpine
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    networks:
      - uptrace

  uptrace:
    container_name: uptrace
    image: "uptrace/uptrace:1.2.4"
    restart: on-failure
    volumes:
      - ./data/uptrace:/var/lib/uptrace
      - ./config/uptrace.yml:/etc/uptrace/uptrace.yml
    # environment:
    #   - DEBUG=1
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - proxy
      - uptrace

  alertmanager:
    container_name: uptrace-alert
    image: prom/alertmanager:v0.24.0
    restart: on-failure
    user: root
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/config.yml
      - ./data/alertmanager:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    networks:
      - uptrace

  otel-collector:
    container_name: uptrace-otel
    image: otel/opentelemetry-collector-contrib:0.66.0
    restart: on-failure
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ./config/otel.yml:/etc/otelcol/config.yaml
    networks:
      - uptrace
      - proxy

  # vector:
  #   container_name: uptrace-vector
  #   image: timberio/vector:0.25.1-alpine
  #   # environment:
  #   #   VECTOR_LOG: DEBUG
  #   volumes:
  #     - ./config/vector.toml:/etc/vector/vector.toml:ro
  #   networks:
  #     - uptrace
  #     - proxy

  # fluent:
  #   container_name: uptrace-fluent
  #   image: fluent/fluent-bit:2.0.6
  #   command:
  #     - "--config=/fluent/fluent.conf"
  #   volumes:
  #     - ./config/fluent.conf:/fluent/fluent.conf:ro
  #   networks:
  #     - uptrace
  #     - proxy

networks:
  uptrace:
    name: uptrace
  proxy:
    external: true
    name: proxy
