services:
  desktop:
    container_name: desktop
    hostname: desktop
    image: zzci/desktop
    restart: always
    volumes:
      - ./work:/work
    devices:
      - /dev/fuse:/dev/fuse
    # privileged: true
    security_opt:
      - seccomp:unconfined
    shm_size: "2gb"
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
